version: "3"
services:
  filebeat:
    container_name: filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:${FILEBEAT_VERSION}
    restart: always
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ..\log\redis:/www/redis/log
      - ..\log\nginx:/www/nginx/log
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    links:
      - etcd_filebeat
      - etcd
    network_mode: host
  etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    restart: always
    ports:
      - 2379:2379
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    links:
      - etcd_filebeat
      - filebeat
  etcd_filebeat:
    image: golang:latest
    volumes:
      - ./awesomeFilebeat:/go/src/examplecom/awesomeFilebeat
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    ports:
      - "8000:8080"
    command: go run /go/src/examplecom/awesomeFilebeat/main.go
    links:
      - filebeat
      - etcd