version: "3"
services:
  es-master:
    container_name: es-master
    hostname: es-master
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    restart: always
    ports:
      # from host to docker
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/master/config/es-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/master/data/:/usr/share/elasticsearch/data/
      - ./elasticsearch/master/logs/:/usr/share/elasticsearch/logs/
      # - ./elasticsearch/mmc.conf:/etc/mmc.conf
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=Asia/Shanghai"

  es-slave1:
    container_name: es-slave1
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    restart: always
    ports:
      - 9201:9200
      - 9301:9300
    volumes:
      - ./elasticsearch/slave1/config/es-slave1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/slave1/data/:/usr/share/elasticsearch/data/
      - ./elasticsearch/slave1/logs/:/usr/share/elasticsearch/logs/
      # - ./elasticsearch/mmc.conf:/etc/mmc.conf
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "TZ=Asia/Shanghai"

  kibana:
    container_name: kibana
    hostname: kibana
    image: kibana:${KIBANA_VERSION}
    restart: always
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - elasticsearch.hosts=http://es-master:9200
      - "TZ=Asia/Shanghai"
    depends_on:
      - es-master
      - es-slave1
  
  logstash:
    container_name: logstash
    hostname: logstash
    image: logstash:${LOGSTASH_VERSION}
    command: logstash -f ./conf/logstash-filebeat.conf
    restart: always
    volumes:
      - ./conf/logstash-filebeat.conf:/usr/share/logstash/conf/logstash-filebeat.conf
    environment:
      - elasticsearch.hosts=http://es-master:9200
      - xpack.monitoring.elasticsearch.hosts=http://es-master:9200
      - "TZ=Asia/Shanghai"
    ports:
      - 5044:5044
    depends_on:
      - es-master
      - es-slave1